content_type with belongs_to fields generator
If entering the wagon generate command proposed in the tutorial in the console, I get the following error:
         gems/locomotivecms_wagon-1.5.8/lib/locomotive/wagon/generators/content_type.rb:54:in `block (2 levels) in extract_fields': undefined method `singularize' for nil:NilClass (NoMethodError)

I could amend file content_type.rb, line 54, but I do not know the exact consequences this might have, as content_type module might be called at some other point.

For the moment, I propose to amend the documentation so that the instructions given to the CLI generate what is supposed to be generated pursuant to the documentation.